- name: "Stop mysql"
  service: "name=mysql state=stopped"

- name: "Update the my.cnf"
  template:
    src: "etc_my.cnf-centos.j2"
    dest: "/etc/my.cnf"
    owner: "root"
    mode: 0644

- name: Start mysql
  service: "name=mysql state=started"