- name: install repo
  yum:
    disable_gpg_check: yes
    name: '{{ mysql_percona_repo_rpm_url }}'

- name: disable mysql module dnf
  shell: "dnf module disable mysql -y"
  when: ansible_distribution_major_version == "8"

- name: enable 57 percna
  shell: "percona-release enable {{item}}"
  with_items:
    - ps-57
    - tools
  when: ansible_distribution_major_version == "8"

- name: "Install percona database server"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "Percona-Server-server-{{mysql_version_major}}{{mysql_version_minor}}"
    - "Percona-Server-client-{{mysql_version_major}}{{mysql_version_minor}}"

- name: "Install percona additional packages"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "percona-toolkit"
    - "percona-xtrabackup-24"

- name: "install mysql python module"
  yum:
    name: "MySQL-python"
  when: ansible_distribution_major_version == '7'

- name: "install mysql python module"
  yum:
    name: "python3-mysql"
  when: ansible_distribution_major_version == '8'

- name: "Adjust permissions of datadir"
  file:
    path: "{{ mysql_datadir }}"
    owner: "mysql"
    group: "mysql"
    mode: 0755
    state: "directory"

- name: "Ensure that percona is running and enabled"
  service:
    name: "mysql"
    state: "started"
    enabled: "yes"
