- name: install repo
  yum:
    name: '{{ mysql_percona_repo_rpm_url }}'

- name: "Install percona database server"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "Percona-Server-server-{{mysql_version_major}}{{mysql_version_minor}}"
    - "Percona-Server-client-{{mysql_version_major}}{{mysql_version_minor}}"

- name: "Install percona additional packages"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "percona-toolkit"
    - "percona-xtrabackup-24"
    - "MySQL-python"

- name: "Adjust permissions of datadir"
  file:
    path: "{{ mysql_datadir }}"
    owner: "mysql"
    group: "mysql"
    mode: 0755
    state: "directory"

- name: "Ensure that percona is running and enabled"
  service:
    name: "mysql"
    state: "started"
    enabled: "yes"
