- name: repository installation
  yum_repository:
    file: "{{ mysql_repo_filename }}" 
    name: "{{ mysql_repo_name }}"
    description: "{{ mysql_repo_desc }}"
    baseurl: "{{ mysql_repo_baseurl }}"
    gpgkey: "{{ mysql_repo_gpgkey }}"
    gpgcheck: "{{ mysql_repo_gpgcheck }}"

- name: "Install percona database server"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "Percona-Server-server-{{mysql_version_major}}{{mysql_version_minor}}"
    - "Percona-Server-client-{{mysql_version_major}}{{mysql_version_minor}}"
    - "Percona-Server-devel-{{mysql_version_major}}{{mysql_version_minor}}"
  when: not mysql_cluster

- name: "Install percona mysql cluster server"
  yum:
    name: "Percona-XtraDB-Cluster-{{mysql_version_major}}{{mysql_version_minor}}"
    state: present
  when: mysql_cluster

- name: "Install percona additional packages"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "percona-toolkit"
    - "percona-xtrabackup-24"
    - "MySQL-python"
    - "pv"

- name: "Adjust permissions of datadir"
  file:
    path: "{{ mysql_datadir }}"
    owner: "mysql"
    group: "mysql"
    mode: 0755
    state: "directory"

- name: "Ensure that percona is running and enabled"
  service:
    name: "mysql"
    state: "started"
    enabled: "yes"
  when: not mysql_cluster
