- name: repository installation
  yum_repository:
    file: "{{ mysql_repo_filename }}" 
    name: "{{ mysql_repo_name }}"
    description: "{{ mysql_repo_desc }}"
    baseurl: "{{ mysql_repo_baseurl }}"
    gpgkey: "{{ mysql_repo_gpgkey }}"
    gpgcheck: "{{ mysql_repo_gpgcheck }}"

- name: "Install percona arbitrator"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "Percona-XtraDB-Cluster-garbd-{{mysql_version_major}}{{mysql_version_minor}}"

- name: "Update the arbitrator config"
  template:
    src: "garb.j2"
    dest: "/etc/sysconfig/garb"
    owner: "root"
    mode: 0600

- name: "Ensure that arbitrator is running and enabled"
  service:
    name: "garb"
    state: "started"
    enabled: "yes"
