---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  tags: 
    - configure
    - install
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- include: install-centos.yml
  tags: install

- include: secure.yml
  tags: secure

- include: configure-centos.yml
  tags: configure

- include: databases.yml
  tags: databases

- include: users.yml
  tags: mysql_users
